version: 2
jobs:
  build:
    docker:
      - image: whill/ros_build_with_visionworks

    shell: /bin/bash
    working_directory: ~/catkin_ws/src/ros_fisheye_image_proc
    environment:
     DEBIAN_FRONTEND: noninteractive

    steps:
      - checkout

      - run:
          name: Prepare libSGM
          command: |
           apt-get update -qq
           apt-get install -qq git cmake
           cd ~
           git clone https://github.com/fixstars/libSGM.git
           mkdir -p libSGM/build
           cd libSGM/build
           cmake -DBUILD_OPENCV_WRAPPER=ON -DLIBSGM_SHARED=ON -DCUDA_ARCH="-arch=sm_70" -DAUTO_DETECT_ARCH=OFF ..
           make && make install
      
      - run:
          name: Resolve dependencies
          command: |
           apt-get update -qq
           rosdep install -y --from-paths .. --ignore-src --rosdistro=melodic

      - run:
          name: catkin_make
          command: |
           source /opt/ros/melodic/setup.bash
           cd ~/catkin_ws
           catkin_make
          
